/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Latihan;

/**
 *
 * @author User
 */
public class kisiuts extends javax.swing.JFrame {
double TOTBAY, harga, jumlahbeli, pot;
String kodemember, kodebrg;
int baris = 0;

    /**
     * Creates new form kisiuts
     */
    public kisiuts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TXTPOT001 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        TXTPOT = new javax.swing.JTextField();
        TXTNAMEPT = new javax.swing.JTextField();
        CBKODEMEMBER = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTVENDOR01 = new javax.swing.JTextField();
        TXTNAMEITEM = new javax.swing.JTextField();
        CBKODEBARANG = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LBL_NAME_OUT_ADMIN = new javax.swing.JLabel();
        LBL_NAME_OUT_PT = new javax.swing.JLabel();
        LBL_VENDOR_OUT = new javax.swing.JLabel();
        LBL_NAME_OUT_ITEM = new javax.swing.JLabel();
        LBL_TOTBAY = new javax.swing.JLabel();
        LBL_AMOUNT_OUT_ORDER = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TXTNAMEADMIN = new javax.swing.JTextField();
        TXTPOT002 = new javax.swing.JTextField();
        TXTHARBARANG = new javax.swing.JTextField();
        TXTORDERITEM = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        BTNSAVE = new javax.swing.JButton();
        BTNEXIT = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNPROCESS = new javax.swing.JButton();
        BTNPLUS = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLEKISIUTS = new javax.swing.JTable();

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTPOT001.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Perusahaan");

        jLabel2.setText("NIK");

        jLabel3.setText("Nama PT");

        jLabel4.setText("Potongan ");

        jLabel5.setText("Kode Member");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        CBKODEMEMBER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kode", "NONE", "VIP", "VVIP" }));
        CBKODEMEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKODEMEMBERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TXTPOT001Layout = new javax.swing.GroupLayout(TXTPOT001);
        TXTPOT001.setLayout(TXTPOT001Layout);
        TXTPOT001Layout.setHorizontalGroup(
            TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TXTPOT001Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TXTPOT001Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TXTPOT001Layout.createSequentialGroup()
                            .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(22, 22, 22)
                            .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CBKODEMEMBER, javax.swing.GroupLayout.Alignment.LEADING, 0, 336, Short.MAX_VALUE)
                                .addComponent(TXTNAMEPT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXTPOT)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TXTPOT001Layout.setVerticalGroup(
            TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TXTPOT001Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTNAMEPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TXTPOT001Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addGroup(TXTPOT001Layout.createSequentialGroup()
                        .addGroup(TXTPOT001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TXTPOT001Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBKODEMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTPOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setText("Vendor");

        jLabel8.setText("Kode Barang");

        jLabel9.setText("Nama Barang");

        TXTVENDOR01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTVENDOR01ActionPerformed(evt);
            }
        });

        TXTNAMEITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNAMEITEMActionPerformed(evt);
            }
        });

        CBKODEBARANG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kode", "MST", "CSSN", "JAPFA" }));
        CBKODEBARANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKODEBARANGActionPerformed(evt);
            }
        });

        jLabel15.setText("Vendor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTVENDOR01)
                            .addComponent(CBKODEBARANG, 0, 220, Short.MAX_VALUE)
                            .addComponent(TXTNAMEITEM)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXTVENDOR01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBKODEBARANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(TXTNAMEITEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setText("Laporan");

        LBL_NAME_OUT_ADMIN.setText("Nama_OUT_Admin");

        LBL_NAME_OUT_PT.setText("Nama_OUT_PT");

        LBL_VENDOR_OUT.setText("Vendor_OUT");

        LBL_NAME_OUT_ITEM.setText("Nama_OUT_Barang");

        LBL_TOTBAY.setText("Total_Pembayaran");

        LBL_AMOUNT_OUT_ORDER.setText("Jumlah_OUT_Order");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(LBL_VENDOR_OUT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBL_TOTBAY))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(LBL_NAME_OUT_ADMIN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBL_NAME_OUT_ITEM))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(LBL_NAME_OUT_PT)
                                .addGap(83, 83, 83)
                                .addComponent(LBL_AMOUNT_OUT_ORDER)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_NAME_OUT_ADMIN)
                    .addComponent(LBL_NAME_OUT_ITEM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_NAME_OUT_PT)
                    .addComponent(LBL_AMOUNT_OUT_ORDER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_VENDOR_OUT)
                    .addComponent(LBL_TOTBAY))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel10.setText("Transaksi");

        jLabel11.setText("Nama Admin");

        jLabel12.setText("Jumlah Order");

        jLabel13.setText("Harga Barang");

        jLabel14.setText("Potongan ");

        TXTNAMEADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNAMEADMINActionPerformed(evt);
            }
        });

        TXTPOT002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPOT002ActionPerformed(evt);
            }
        });

        TXTHARBARANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHARBARANGActionPerformed(evt);
            }
        });

        TXTORDERITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTORDERITEMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTNAMEADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TXTHARBARANG, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(TXTORDERITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTPOT002, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTNAMEADMIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPOT002, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TXTHARBARANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTORDERITEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        BTNSAVE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNSAVE.setText("Simpan");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        BTNEXIT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNEXIT.setText("Keluar");
        BTNEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEXITActionPerformed(evt);
            }
        });

        BTNDELETE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNDELETE.setText("Hapus");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        BTNPROCESS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNPROCESS.setText("Proses");
        BTNPROCESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPROCESSActionPerformed(evt);
            }
        });

        BTNPLUS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNPLUS.setText("Tambah");
        BTNPLUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPLUSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(BTNPROCESS)
                .addGap(55, 55, 55)
                .addComponent(BTNSAVE)
                .addGap(59, 59, 59)
                .addComponent(BTNDELETE)
                .addGap(51, 51, 51)
                .addComponent(BTNPLUS)
                .addGap(53, 53, 53)
                .addComponent(BTNEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSAVE)
                    .addComponent(BTNEXIT)
                    .addComponent(BTNDELETE)
                    .addComponent(BTNPROCESS)
                    .addComponent(BTNPLUS))
                .addContainerGap())
        );

        TABLEKISIUTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Admin", "Nama PT", "Vandor", "Nama Barang", "Jumlah", "Total"
            }
        ));
        jScrollPane2.setViewportView(TABLEKISIUTS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTPOT001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTPOT001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TXTNAMEITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNAMEITEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNAMEITEMActionPerformed

    private void TXTVENDOR01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTVENDOR01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTVENDOR01ActionPerformed

    private void CBKODEBARANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKODEBARANGActionPerformed
        // TODO add your handling code here:
        String kodebarang, namabarang, Vendor;
        
        kodebarang=String.valueOf(CBKODEBARANG.getSelectedItem());
        
        if(kodebarang.equals("MST")){
           namabarang ="Petronas" ;
           Vendor = "Rayi Putra";
        }else
            if(kodemember.equals("CSSN")){
            namabarang ="Pertamina" ;
            Vendor = "Surya";
            }else
                if(kodemember.equals("JAPFA")){
                     namabarang ="So Nice" ;
                     Vendor = "Denny";
                        }else {
                             namabarang ="Tidak Ada" ;
                             Vendor = "--";
                        }
        TXTNAMEITEM.setText(""+namabarang);
        TXTVENDOR01.setText(""+Vendor);
    }//GEN-LAST:event_CBKODEBARANGActionPerformed

    private void TXTNAMEADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNAMEADMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNAMEADMINActionPerformed

    private void TXTPOT002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPOT002ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPOT002ActionPerformed

    private void TXTHARBARANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHARBARANGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTHARBARANGActionPerformed

    private void TXTORDERITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTORDERITEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTORDERITEMActionPerformed

    private void BTNEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEXITActionPerformed
        // TODO add your handling code here
         dispose();
    }//GEN-LAST:event_BTNEXITActionPerformed

    private void BTNPROCESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPROCESSActionPerformed
        // TODO add your handling code here:
        String kodemember, namapt, kodebarang, namabarang, Vendor;
        double potongan;
        
        kodebarang=String.valueOf(CBKODEBARANG.getSelectedItem());
        kodemember=String.valueOf(CBKODEMEMBER.getSelectedItem());
        
        LBL_NAME_OUT_ADMIN.setText(TXTNAMEADMIN.getText());
        LBL_NAME_OUT_PT.setText(TXTNAMEPT.getText());
        LBL_VENDOR_OUT.setText(TXTVENDOR01.getText());
        LBL_NAME_OUT_ITEM.setText(TXTNAMEITEM.getText());
        LBL_AMOUNT_OUT_ORDER.setText(TXTORDERITEM.getText());
        LBL_TOTBAY.setText(LBL_TOTBAY.getText());
        
        TOTBAY = (harga * jumlahbeli)- pot;
       
          if(kodemember.equals("NONE")){
           namapt ="Ajisurya Group" ;
           potongan = 50;
        }else
            if(kodemember.equals("VIP")){
                namapt="Arya salim Group";
                potongan = 40;
            }else
                if(kodemember.equals("VVIP")){
                    namapt="DR.Karni";
                    potongan = 45;
                        }else {
                                namapt = "Tidak ada";
                                potongan = 0;
                        }
        TXTNAMEPT.setText(""+namapt);
        TXTPOT.setText(""+potongan);
        
         if(kodebarang.equals("MST")){
           namabarang ="Petronas" ;
           Vendor = "Rayi";
        }else
            if(kodemember.equals("CSSN")){
            namabarang ="Pertamina" ;
            Vendor = "Surya";
            }else
                if(kodemember.equals("JAPFA")){
                     namabarang ="So Nice" ;
                     Vendor = "Denny";
                        }else {
                             namabarang ="Tidak Ada" ;
                             Vendor = "--";
                        }
        TXTNAMEITEM.setText(""+namabarang);
        TXTVENDOR01.setText(""+Vendor);
    }//GEN-LAST:event_BTNPROCESSActionPerformed

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        TABLEKISIUTS.setValueAt(LBL_NAME_OUT_ADMIN.getText(), baris, 0);
        TABLEKISIUTS.setValueAt(LBL_NAME_OUT_PT.getText(), baris, 1);
        TABLEKISIUTS.setValueAt(LBL_VENDOR_OUT.getText(), baris, 2);
        TABLEKISIUTS.setValueAt(LBL_NAME_OUT_ITEM.getText(), baris, 3);
        TABLEKISIUTS.setValueAt(LBL_AMOUNT_OUT_ORDER.getText(), baris, 4);
        TABLEKISIUTS.setValueAt(LBL_TOTBAY.getText(), baris, 5);
        
        baris++;
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        TABLEKISIUTS.setValueAt (null, TABLEKISIUTS.getSelectedRow(), 0);
        TABLEKISIUTS.setValueAt (null, TABLEKISIUTS.getSelectedRow(), 1);
        TABLEKISIUTS.setValueAt (null, TABLEKISIUTS.getSelectedRow(), 2);
        TABLEKISIUTS.setValueAt (null, TABLEKISIUTS.getSelectedRow(), 3);
        TABLEKISIUTS.setValueAt (null, TABLEKISIUTS.getSelectedRow(), 4);
        TABLEKISIUTS.setValueAt (null, TABLEKISIUTS.getSelectedRow(), 5);
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void CBKODEMEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKODEMEMBERActionPerformed
        // TODO add your handling code here:
        String kodemember,namapt;
        double potongan;
       
        
        kodemember=String.valueOf(CBKODEMEMBER.getSelectedItem());
        
        if(kodemember.equals("NONE")){
           namapt ="Ajisurya Group" ;
           potongan = 50;
        }else
            if(kodemember.equals("VIP")){
                namapt="Arya salim Group";
                potongan = 40;
            }else
                if(kodemember.equals("VVIP")){
                    namapt="Karni Lawyer Group";
                    potongan = 45;
                        }else {
                                namapt = "Tidak ada";
                                potongan = 0;
                        }
        TXTNAMEPT.setText(""+namapt);
        TXTPOT.setText(""+potongan);
    }//GEN-LAST:event_CBKODEMEMBERActionPerformed

    private void BTNPLUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPLUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNPLUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kisiuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kisiuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kisiuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kisiuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kisiuts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNEXIT;
    private javax.swing.JButton BTNPLUS;
    private javax.swing.JButton BTNPROCESS;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JComboBox<String> CBKODEBARANG;
    private javax.swing.JComboBox<String> CBKODEMEMBER;
    private javax.swing.JLabel LBL_AMOUNT_OUT_ORDER;
    private javax.swing.JLabel LBL_NAME_OUT_ADMIN;
    private javax.swing.JLabel LBL_NAME_OUT_ITEM;
    private javax.swing.JLabel LBL_NAME_OUT_PT;
    private javax.swing.JLabel LBL_TOTBAY;
    private javax.swing.JLabel LBL_VENDOR_OUT;
    private javax.swing.JTable TABLEKISIUTS;
    private javax.swing.JTextField TXTHARBARANG;
    private javax.swing.JTextField TXTNAMEADMIN;
    private javax.swing.JTextField TXTNAMEITEM;
    private javax.swing.JTextField TXTNAMEPT;
    private javax.swing.JTextField TXTORDERITEM;
    private javax.swing.JTextField TXTPOT;
    private javax.swing.JPanel TXTPOT001;
    private javax.swing.JTextField TXTPOT002;
    private javax.swing.JTextField TXTVENDOR01;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
