package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import java.sql.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane; 
import java.sql.SQLException;
import javax.swing.JTable;
 
public class DBDeleteFormGUI extends javax.swing.JFrame {
     String user="root";         
     String pswd ="";         
     String host="localhost";         
     String db="db_datasenin";         
     String url="";         
     private Connection Lconnection=null;     
     private JTable table=null;
   
    /**
     * Creates new form DBDeleteGUI
     */
    public DBDeleteFormGUI() {
        initComponents();
        
    try { 
           Class.forName("com.mysql.jdbc.Driver");             
           url="jdbc:mysql://"+ host +"/"+ db +"?user=" + user + "&password="+ pswd; 
           
           Lconnection=DriverManager.getConnection(url);         
        } 
 
        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        } 
 
        catch (SQLException e){             
            System.out.println("koneksi gagal:" +                  
                    e.toString());         
        } 
 
        tampilTabel(); 

        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNDELETE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNDELETE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNDELETE.setText("Delete");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(BTNDELETE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNDELETE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        String usrID = table.getValueAt(table.getSelectedRow(),0).toString();           

        try {  
            PreparedStatement pStatement = null;             
            String sql ="DELETE FROM tb_datasenin Where Nama=? ";             
            pStatement = Lconnection.prepareStatement(sql);
            pStatement.setString(1, usrID);
 
            int intTambah= pStatement.executeUpdate();             
            if (intTambah>0)                 
              JOptionPane.showMessageDialog(this,
                "Hapus data sukses", "Informasi",
                 JOptionPane.INFORMATION_MESSAGE);             
            else                 
             JOptionPane.showMessageDialog(this,
                 "Hapus data gagal", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                    pStatement.close(); 
             tampilTabel();         
           } 
 
            catch (SQLException e){             
           System.out.println("koneksi gagal " + e.toString());         
           } 
 
    }//GEN-LAST:event_BTNDELETEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
              new DBDeleteFormGUI().setVisible(true);
         }
      });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

                  private Object[][] getData(){ 
                  Object[][] data1= null; 
 
                 try {
                  Connection conn=DriverManager.getConnection(url);
                  Statement st = Lconnection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);             
                  ResultSet rs = st.executeQuery("Select * tb_datasenin"); 
                  rs.last();             
                  int rowCount= rs.getRow();            
                  rs.beforeFirst();
                  data1= new Object[rowCount][5];             
                  int no=-1;             
                  while (rs.next()) {                 
                  no=no+1;
                  data1[no][0]=rs.getString("Nama");                                
                  data1[no][1]=rs.getString("Alamat");                 
                  data1[no][2]=rs.getString("Telepon");
                  data1[no][3]=rs.getString("Handphone");  
                  data1[no][4]=rs.getString("Prodi"); 
                  }           
                  st.close();        
                 } 
                  catch (SQLException e){             
                System.out.println("koneksi gagal " + e.toString());        
                } 
        return data1;     
         } 

         private void tampilTabel() { 
         String[] columnNames = {"Nama", "Telepon", "Handphone", "Alamat",  "Prodi"}; 
         table = new JTable(getData(), columnNames);
         jScrollPane1.setViewportView(table);
}
}
