package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
 import java.sql.Connection; 
 import java.sql.DriverManager; 
 import java.sql.PreparedStatement; 
 import java.sql.ResultSet; 
 import java.sql.SQLException; 
 import java.sql.Statement; 
 import javax.swing.JOptionPane; 
 import javax.swing.JTable; 

public class DBUpdateGUI extends javax.swing.JFrame {
    String user="root";         
    String pswd ="";         
    String host="localhost";         
    String db="db_datasenin";     
    String url=""; 
    private Connection Lconnection=null;
    /**
     * Creates new form Editdata
     */
    public DBUpdateGUI() {
        initComponents();
        
        BTNSAVE.setEnabled(false);         
        try { 
 
            Class.forName("com.mysql.jdbc.Driver");             
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd; 
            Lconnection=DriverManager.getConnection(url);         
        } 

        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        }  
        catch (SQLException e){             
            System.out.println("koneksi gagal:" +                  
                  e.toString());         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLNAME = new javax.swing.JLabel();
        LBLTELEPHONE = new javax.swing.JLabel();
        LBLHP = new javax.swing.JLabel();
        LBLALAMAT = new javax.swing.JLabel();
        LBLPRODI = new javax.swing.JLabel();
        BTNSAVE = new javax.swing.JButton();
        TXTNAMAMHS = new javax.swing.JTextField();
        TXTHP = new javax.swing.JTextField();
        TXTTELEPHONE = new javax.swing.JTextField();
        TXTADDRESS = new javax.swing.JTextField();
        TXTPRODY = new javax.swing.JTextField();
        LBLNAME1 = new javax.swing.JLabel();
        TXTIDMHS = new javax.swing.JTextField();
        LBLNAME2 = new javax.swing.JLabel();
        BTNCEKID = new javax.swing.JButton();
        BTNCEKNAMA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        LBLNAME.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME.setText("Data Mahasiswa");

        LBLTELEPHONE.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE.setText("Telepon");

        LBLHP.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLHP.setForeground(new java.awt.Color(255, 255, 255));
        LBLHP.setText("Handphone");

        LBLALAMAT.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLALAMAT.setForeground(new java.awt.Color(255, 255, 255));
        LBLALAMAT.setText("Alamat");

        LBLPRODI.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLPRODI.setForeground(new java.awt.Color(255, 255, 255));
        LBLPRODI.setText("Prodi");

        BTNSAVE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNSAVE.setText("Simpan");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        LBLNAME1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME1.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME1.setText("Nama Mahasiswa");

        LBLNAME2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME2.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME2.setText("ID Mahasiswa");

        BTNCEKID.setText("Cek ID");
        BTNCEKID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKIDActionPerformed(evt);
            }
        });

        BTNCEKNAMA.setText("Cek Nama");
        BTNCEKNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKNAMAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BTNSAVE))
                    .addComponent(LBLNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LBLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBLPRODI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBLTELEPHONE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBLALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLNAME1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBLNAME2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TXTNAMAMHS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(BTNCEKNAMA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTTELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTHP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTPRODY, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TXTIDMHS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNCEKID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LBLNAME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBLNAME2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLNAME1)
                            .addComponent(TXTNAMAMHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLTELEPHONE)
                            .addComponent(TXTTELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLHP)
                            .addComponent(TXTHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLPRODI)
                            .addComponent(TXTPRODY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNSAVE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTIDMHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNCEKNAMA)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
         String user="root";         
         String pswd ="";         
         String host="localhost";         
         String db="db_datasenin";         
         String url=""; 
         
           try {             
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;             
            Connection conn=DriverManager.getConnection(url); 
            PreparedStatement pStatement = conn.prepareStatement("UPDATE tb_datasenin SET Nama=?,Alamat=?,Telepon=?,Handphone=?,Prodi=? WHERE id=?");
            
             pStatement.setString(1, TXTNAMAMHS.getText());             
             pStatement.setString(2, TXTTELEPHONE.getText()); 
             pStatement.setString(3, TXTHP.getText());             
             pStatement.setString(4, TXTADDRESS.getText()); 
             pStatement.setString(5, TXTPRODY.getText());             
             pStatement.setString(6, TXTIDMHS.getText()); 
             
             if (pStatement.executeUpdate()>0)                 
                 JOptionPane.showMessageDialog(this,                    
                   "Edit sukses", "Informasi",                    
                   JOptionPane.INFORMATION_MESSAGE);             
             else                 
                 JOptionPane.showMessageDialog(this,                    
                   "Edit gagal", "Informasi",                    
                   JOptionPane.INFORMATION_MESSAGE); 
 
            pStatement.close();             
            TXTNAMAMHS.setText("");             
            TXTTELEPHONE.setText("");             
            TXTHP.setText("");             
            TXTADDRESS.setText("");         
            TXTPRODY.setText("");   
            
           }        
           catch(ClassNotFoundException e) {             
               System.out.println("jdbc.Driver tidak ditemukan");        
         } 
 
           catch (SQLException e){             
               System.out.println("koneksi gagal " + e.toString()); 
      }
             
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNCEKIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKIDActionPerformed
        // TODO add your handling code here:
        try {             
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery (" Select * from tb_datasenin" + "where id='" + TXTIDMHS.getText() + "'");        
             if (rs.next()) {                 
                 BTNCEKID.setEnabled(true);
                 TXTNAMAMHS.setText(rs.getString("Nama"));                 
                 TXTADDRESS.setText(rs.getString("Alamat"));                 
                 TXTTELEPHONE.setText(rs.getString("Telephone"));                 
                 TXTHP.setText(rs.getString("Handphone"));                 
                 TXTIDMHS.setText(rs.getString("id"));             
                 TXTPRODY.setText(rs.getString("Prodi"));     
             } else {                 
                 JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
           
                BTNSAVE.setEnabled(false);                 
                TXTNAMAMHS.setText("");                 
                TXTADDRESS.setText(""); 
                TXTTELEPHONE.setText("");                 
                TXTHP.setText("");                 
                TXTIDMHS.setText("");    
                TXTNAMAMHS.requestFocus();  
       }         
      }            
       catch (SQLException e){             
      System.out.println("koneksi gagal " + e.toString()); 
       }
    }//GEN-LAST:event_BTNCEKIDActionPerformed

    private void BTNCEKNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKNAMAActionPerformed
        // TODO add your handling code here:
        try {             
    Statement st = Lconnection.createStatement();             
    ResultSet rs = st.executeQuery 
   ("Select * from tb_datasenin" + "where nama like('%" +TXTNAMAMHS.getText() + "%')");
 
            if (rs.next()) {                 
            BTNCEKID.setEnabled(true);   
            TXTIDMHS.setText(rs.getString("id"));  
            TXTNAMAMHS.setText(rs.getString("Nama"));                 
            TXTADDRESS.setText(rs.getString("Alamat"));                  
            TXTTELEPHONE.setText(rs.getString("Telephone"));                 
            TXTHP.setText(rs.getString("Handphone"));                 
            TXTPRODY.setText(rs.getString("Prodi"));             
        } else {                 
          JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE); 
              
              BTNSAVE.setEnabled(false);
              TXTNAMAMHS.setText("");  
              TXTADDRESS.setText("");                 
              TXTTELEPHONE.setText("");                 
              TXTHP.setText("");                 
              TXTIDMHS.setText("");                 
              TXTPRODY.setText("");             
        }         
      }            
         catch (SQLException e){             
             System.out.println("koneksi gagal " + e.toString());
      } 
    }//GEN-LAST:event_BTNCEKNAMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBUpdateGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCEKID;
    private javax.swing.JButton BTNCEKNAMA;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JLabel LBLALAMAT;
    private javax.swing.JLabel LBLHP;
    private javax.swing.JLabel LBLNAME;
    private javax.swing.JLabel LBLNAME1;
    private javax.swing.JLabel LBLNAME2;
    private javax.swing.JLabel LBLPRODI;
    private javax.swing.JLabel LBLTELEPHONE;
    private javax.swing.JTextField TXTADDRESS;
    private javax.swing.JTextField TXTHP;
    private javax.swing.JTextField TXTIDMHS;
    private javax.swing.JTextField TXTNAMAMHS;
    private javax.swing.JTextField TXTPRODY;
    private javax.swing.JTextField TXTTELEPHONE;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
