package ProgramDBmonday2022;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import java.sql.*; 
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.sql.Statement; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane;

public class DBDeleteData extends javax.swing.JFrame {
    String user="root";         
    String pswd ="";         
    String host="localhost";         
    String db="Db_DataSenin";         
    String url="";         
    private Connection Lconnection=null;         
  
    /**
     * Creates new form DBDeleteGUI
     */
    public DBDeleteData(){
        initComponents();
        
     //   BTNDELETE.setEnabled(false);         
        try { 
 
            Class.forName("com.mysql.jdbc.Driver");             
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd; 
            Lconnection=DriverManager.getConnection(url);         
        } 

        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        }  
        catch (SQLException e){             
            System.out.println("koneksi gagal:" +                  
                  e.toString());         
        }
    //tampilTabel ();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        LBLTELEPHONE = new javax.swing.JLabel();
        LBLHP = new javax.swing.JLabel();
        LBLALAMAT = new javax.swing.JLabel();
        BTNDELETE = new javax.swing.JButton();
        TXTNAMA = new javax.swing.JTextField();
        TXTHP = new javax.swing.JTextField();
        TXTTELEPHONE = new javax.swing.JTextField();
        TXTADDRESS = new javax.swing.JTextField();
        LBLNAME1 = new javax.swing.JLabel();
        BTNCEKID = new javax.swing.JButton();
        BTNCEKNAMA = new javax.swing.JButton();
        TXTID = new javax.swing.JTextField();
        LBLNAME2 = new javax.swing.JLabel();
        LBLPRODI = new javax.swing.JLabel();
        TXTPRODI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel1.setBackground(new java.awt.Color(153, 153, 0));

        LBLTELEPHONE.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLTELEPHONE.setForeground(new java.awt.Color(255, 255, 255));
        LBLTELEPHONE.setText("Telepon");

        LBLHP.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLHP.setForeground(new java.awt.Color(255, 255, 255));
        LBLHP.setText("Handphone");

        LBLALAMAT.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLALAMAT.setForeground(new java.awt.Color(255, 255, 255));
        LBLALAMAT.setText("Alamat");

        BTNDELETE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNDELETE.setText("Delete");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        LBLNAME1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME1.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME1.setText("Nama");

        BTNCEKID.setText("Cek ID");
        BTNCEKID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKIDActionPerformed(evt);
            }
        });

        BTNCEKNAMA.setText("Cek Nama");
        BTNCEKNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKNAMAActionPerformed(evt);
            }
        });

        LBLNAME2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLNAME2.setForeground(new java.awt.Color(255, 255, 255));
        LBLNAME2.setText("ID ");

        LBLPRODI.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        LBLPRODI.setForeground(new java.awt.Color(255, 255, 255));
        LBLPRODI.setText("Prodi");

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLTELEPHONE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLNAME1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLNAME2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LBLPRODI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTID)
                    .addComponent(TXTADDRESS, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(TXTTELEPHONE, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(TXTHP, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(TXTNAMA)
                    .addComponent(TXTPRODI, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNCEKID, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(BTNCEKNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(BTNDELETE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BTNCEKID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLNAME2))))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCEKNAMA)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LBLNAME1)
                        .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLTELEPHONE)
                    .addComponent(TXTTELEPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLHP)
                    .addComponent(TXTHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPRODI)
                    .addComponent(TXTPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BTNDELETE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:                          
              try {
              PreparedStatement pStatement = null;             
              String sql ="DELETE FROM tb_datasenin WHERE ID=? ";             
              pStatement = Lconnection.prepareStatement(sql); 
            
             // pStatement.setString(1, TXTID);  
             
             int intTambah= pStatement.executeUpdate();                          
             if (intTambah>0)                 
                 JOptionPane.showMessageDialog(this,                    
                   "Edit sukses", "Informasi",                    
                   JOptionPane.INFORMATION_MESSAGE);             
             else                 
                 JOptionPane.showMessageDialog(this,                    
                   "Edit gagal", "Informasi",                    
                   JOptionPane.INFORMATION_MESSAGE); 
 
            pStatement.close();             
                   
           }        
      
           catch (SQLException e){             
               System.out.println("koneksi gagal " + e.toString()); 
      }
             
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void BTNCEKIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKIDActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery (" Select * from ProgramDBMonday2022" + "where id='" + TXTID.getText() + "'");
            if (rs.next()) {
                BTNDELETE.setEnabled(true);
                TXTID.setText(rs.getString("id"));
                TXTNAMA.setText(rs.getString("Nama"));
                TXTADDRESS.setText(rs.getString("Alamat"));
                TXTTELEPHONE.setText(rs.getString("Telephone"));
                TXTHP.setText(rs.getString("Handphone"));
                TXTPRODI.setText(rs.getString("Prodi"));
              
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNDELETE.setEnabled(false);
                TXTID.setText("");
                TXTNAMA.setText("");
                TXTADDRESS.setText("");
                TXTTELEPHONE.setText("");
                TXTHP.setText("");
                TXTPRODI.setText("");
                TXTNAMA.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKIDActionPerformed

    private void BTNCEKNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKNAMAActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from ProgramDBMonday2022" + "where nama like('%" +TXTNAMA.getText() + "%')");

            if (rs.next()) {
                BTNCEKID.setEnabled(true);
                TXTID.setText(rs.getString("ID"));
                TXTNAMA.setText(rs.getString("Nama"));
                TXTADDRESS.setText(rs.getString("Alamat"));
                TXTTELEPHONE.setText(rs.getString("Telephone"));
                TXTHP.setText(rs.getString("Handphone"));
                TXTPRODI.setText(rs.getString("Prodi"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNDELETE.setEnabled(false);
                TXTID.setText("");
                TXTNAMA.setText("");
                TXTADDRESS.setText("");
                TXTTELEPHONE.setText("");
                TXTHP.setText("");
                TXTPRODI.setText("");
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKNAMAActionPerformed

    /**
     * @param args the command line arguments
     */
    
         public static void main(String args[]) { 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new DBDeleteData().setVisible(true);
        } 
           });
          }
               
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCEKID;
    private javax.swing.JButton BTNCEKNAMA;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JLabel LBLALAMAT;
    private javax.swing.JLabel LBLHP;
    private javax.swing.JLabel LBLNAME1;
    private javax.swing.JLabel LBLNAME2;
    private javax.swing.JLabel LBLPRODI;
    private javax.swing.JLabel LBLTELEPHONE;
    private javax.swing.JTextField TXTADDRESS;
    private javax.swing.JTextField TXTHP;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTNAMA;
    private javax.swing.JTextField TXTPRODI;
    private javax.swing.JTextField TXTTELEPHONE;
    // End of variables declaration//GEN-END:variables
 }
