/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programming2monday;

/**
 *
 * @author User
 */
public class penyewaandvd extends javax.swing.JFrame {

    private double biayadaftar;

    /**
     * Creates new form penyewaandvd
     */
    public penyewaandvd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkodepelanggan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtbiayadaftar = new javax.swing.JTextField();
        btnproses1 = new javax.swing.JButton();
        CBKodePlg = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblnodvd = new javax.swing.JLabel();
        txtnodvd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbljumlahhari = new javax.swing.JLabel();
        txtJenisFilm = new javax.swing.JTextField();
        txtJudulFilm = new javax.swing.JTextField();
        txtbiayasewa = new javax.swing.JTextField();
        txtjumlahhari = new javax.swing.JTextField();
        btnproses2 = new javax.swing.JButton();
        CBNoDVD = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnHitung1 = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Pelanggan ");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Biaya Daftar");

        txtkodepelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodepelangganActionPerformed(evt);
            }
        });

        btnproses1.setText("Proses");
        btnproses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproses1ActionPerformed(evt);
            }
        });

        CBKodePlg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AAAA", "BBBB" }));
        CBKodePlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKodePlgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(txtStatus)
                            .addComponent(txtbiayadaftar))
                        .addGap(395, 395, 395))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtkodepelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBKodePlg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnproses1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(336, 336, 336))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkodepelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnproses1)
                    .addComponent(CBKodePlg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtbiayadaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        lblnodvd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblnodvd.setForeground(new java.awt.Color(255, 255, 255));
        lblnodvd.setText("No DVD");

        txtnodvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnodvdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Film");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Judul Film");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Biaya Sewa");

        lbljumlahhari.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbljumlahhari.setForeground(new java.awt.Color(255, 255, 255));
        lbljumlahhari.setText("Jumlah Hari");

        txtJenisFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisFilmActionPerformed(evt);
            }
        });

        txtjumlahhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahhariActionPerformed(evt);
            }
        });

        btnproses2.setText("Proses");
        btnproses2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproses2ActionPerformed(evt);
            }
        });

        CBNoDVD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1111", "2222", "3333", "4444", "5555" }));
        CBNoDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNoDVDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnodvd)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(lbljumlahhari))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtJudulFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(txtJenisFilm)
                        .addComponent(txtbiayasewa)
                        .addComponent(txtjumlahhari))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtnodvd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBNoDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnproses2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnodvd)
                    .addComponent(txtnodvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnproses2)
                    .addComponent(CBNoDVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtJenisFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtJudulFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtbiayasewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljumlahhari)
                    .addComponent(txtjumlahhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Total Bayar ");

        txtTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBayarActionPerformed(evt);
            }
        });

        btnHitung.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnHitung1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHitung1.setText("Hitung");
        btnHitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitung1ActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addGap(49, 49, 49)
                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHitung)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnHitung1)
                .addGap(52, 52, 52)
                .addComponent(btnhapus)
                .addGap(39, 39, 39)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHitung)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHitung1)
                        .addComponent(btnhapus))
                    .addComponent(btnExit))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkodepelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodepelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodepelangganActionPerformed

    private void txtnodvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnodvdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnodvdActionPerformed

    private void txtJenisFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisFilmActionPerformed

    private void txtjumlahhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahhariActionPerformed

    private void txtTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBayarActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        double totalbayar,biayadaftar,biayasewa;
        int jumlahhari;

        jumlahhari=Integer.parseInt(txtjumlahhari.getText());
        biayadaftar = Double.parseDouble(txtbiayadaftar.getText());
        biayasewa = Double.parseDouble(txtbiayasewa.getText());

        totalbayar = biayadaftar + (biayasewa * jumlahhari);

        txtTotalBayar.setText(""+totalbayar);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnHitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitung1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitung1ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnproses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproses1ActionPerformed
        // TODO add your handling code here:
       String kodepelanggan,status;
       double biayadaftar;

        kodepelanggan=String.valueOf(txtkodepelanggan.getText());
        biayadaftar=Double.parseDouble(txtbiayadaftar.getText());

        if(kodepelanggan.equals("AAAA")){
            status ="BARU";
            biayadaftar =50000;
        }else
        if(kodepelanggan.equals("BBBB")){
            status ="LAMA";
            biayadaftar =300000;
        }else {
            status = "Tidak ada";
            biayadaftar = 0;
        }

        txtStatus.setText(""+status);
    }//GEN-LAST:event_btnproses1ActionPerformed

    private void btnproses2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproses2ActionPerformed
        // TODO add your handling code here:
        String jenisfilm,judulfilm;
        double nodvd,biayasewa,totalbayar;
        int jumlahhari;

        nodvd=Double.parseDouble(txtnodvd.getText());
        jumlahhari=Integer.parseInt(txtjumlahhari.getText());

        if(txtnodvd.equals("1111")){
            jenisfilm ="ACTION";
            judulfilm ="IRON MAN";
            biayasewa =25000;
        }else
        if(txtnodvd.equals("2222")){
            jenisfilm ="DRAMA";
            judulfilm ="DILAN 1990";
            biayasewa =10000;
        }else
        if(txtnodvd.equals("3333")){
            jenisfilm ="KOLOSAL";
            judulfilm ="THE LORD OF THE RINGS";
            biayasewa =15000;
        }else
        if(txtnodvd.equals("4444")){
            jenisfilm ="KOMEDI";
            judulfilm ="WARKOP REBORN";
            biayasewa =17500;
        }else
        if(txtnodvd.equals("5555")){
            jenisfilm ="HOROR";
            judulfilm ="THE NUN";
            biayasewa =25000;
        }else {
            jenisfilm ="Tidak ada";
            judulfilm ="0";
            biayasewa =0;
        }

        txtJenisFilm.setText(""+jenisfilm);
        txtJudulFilm.setText(""+judulfilm);
        txtbiayasewa.setText(""+biayasewa);

        totalbayar = biayadaftar + (biayasewa * jumlahhari);

        txtTotalBayar.setText(""+totalbayar);
    }//GEN-LAST:event_btnproses2ActionPerformed

    private void CBNoDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNoDVDActionPerformed
        // TODO add your handling code here:
         String jenisfilm,judulfilm;
        double nodvd,biayasewa,totalbayar;
        int jumlahhari;

        nodvd=Double.parseDouble(txtnodvd.getText());
        jumlahhari=Integer.parseInt(txtjumlahhari.getText());

        if(txtnodvd.equals("1111")){
            jenisfilm ="ACTION";
            judulfilm ="IRON MAN";
            biayasewa =25000;
        }else
        if(txtnodvd.equals("2222")){
            jenisfilm ="DRAMA";
            judulfilm ="DILAN 1990";
            biayasewa =10000;
        }else
        if(txtnodvd.equals("3333")){
            jenisfilm ="KOLOSAL";
            judulfilm ="THE LORD OF THE RINGS";
            biayasewa =15000;
        }else
        if(txtnodvd.equals("4444")){
            jenisfilm ="KOMEDI";
            judulfilm ="WARKOP REBORN";
            biayasewa =17500;
        }else
        if(txtnodvd.equals("5555")){
            jenisfilm ="HOROR";
            judulfilm ="THE NUN";
            biayasewa =25000;
        }else {
            jenisfilm ="Tidak ada";
            judulfilm ="0";
            biayasewa =0;
        }

        txtJenisFilm.setText(""+jenisfilm);
        txtJudulFilm.setText(""+judulfilm);
        txtbiayasewa.setText(""+biayasewa);

        totalbayar = biayadaftar + (biayasewa * jumlahhari);

        txtTotalBayar.setText(""+totalbayar);
    }//GEN-LAST:event_CBNoDVDActionPerformed

    private void CBKodePlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKodePlgActionPerformed
        // TODO add your handling code here:
       String kodepelanggan,status;
       double biayadaftar;

        kodepelanggan=String.valueOf(txtkodepelanggan.getText());
        biayadaftar=Double.parseDouble(txtbiayadaftar.getText());

        if(kodepelanggan.equals("AAAA")){
            status ="BARU";
            biayadaftar =50000;
        }else
        if(kodepelanggan.equals("BBBB")){
            status ="LAMA";
            biayadaftar =300000;
        }else {
            status = "Tidak ada";
            biayadaftar = 0;
        }

        txtStatus.setText(""+status);
    }//GEN-LAST:event_CBKodePlgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penyewaandvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penyewaandvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penyewaandvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penyewaandvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penyewaandvd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBKodePlg;
    private javax.swing.JComboBox<String> CBNoDVD;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitung1;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnproses1;
    private javax.swing.JButton btnproses2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lbljumlahhari;
    private javax.swing.JLabel lblnodvd;
    private javax.swing.JTextField txtJenisFilm;
    private javax.swing.JTextField txtJudulFilm;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtbiayadaftar;
    private javax.swing.JTextField txtbiayasewa;
    private javax.swing.JTextField txtjumlahhari;
    private javax.swing.JTextField txtkodepelanggan;
    private javax.swing.JTextField txtnodvd;
    // End of variables declaration//GEN-END:variables
}
