/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_Programming2;

import java.sql.*; 
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
/**
 *
 * @author User
 */
public class CetakReport extends javax.swing.JFrame {
 int baris = 0;
 String user="root";         
 String pswd ="";         
 String host="localhost";         
 String db="db_jerseybola";         
 String url=""; 
 private Connection Lconnection=null;
 private JTable table=null;
    /**
     * Creates new form TBCetakReport
     */
    public CetakReport() {
        initComponents();
        
        Dimension screenSize =
        Toolkit.getDefaultToolkit().getScreenSize();       
         Dimension frameSize = this.getSize();
         if (frameSize.height > screenSize.height) {
             frameSize.height = screenSize.height;
         }
         if (frameSize.width > screenSize.width) {
             frameSize.width = screenSize.width;
         }
          this.setLocation(
                 (screenSize.width - frameSize.width) / 2,
                 (screenSize.height - frameSize.height) / 2);
         
         try { 
            Class.forName("com.mysql.jdbc.Driver");             
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd; 
            Lconnection=DriverManager.getConnection(url);         
        } 
        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        }  
        catch (SQLException e){             
            System.out.println("koneksi gagal:" + e.toString());         
        }
      tampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BTNSAVE = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNREAD = new javax.swing.JButton();
        BTNEXIT = new javax.swing.JButton();
        TXTNIK04 = new javax.swing.JTextField();
        TXTNAMA04 = new javax.swing.JTextField();
        TXTJNSMEMBER04 = new javax.swing.JTextField();
        TXTMERK04 = new javax.swing.JTextField();
        TXTTIPE04 = new javax.swing.JTextField();
        TXTHARGA04 = new javax.swing.JTextField();
        TXTTOTBIA04 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbljersey = new javax.swing.JTable();
        BTNCEKNIK = new javax.swing.JButton();
        BTNCEKNAMA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\rudiger.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cetak Report");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NIK Cust");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nama Cust");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Jenis Member");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Merk Jersey");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Tipe Jersey");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Harga Jersey");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Total Biaya");

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        BTNSAVE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNSAVE.setText("Simpan");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        BTNDELETE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNDELETE.setText("Hapus");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        BTNEDIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNEDIT.setText("Edit");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNREAD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNREAD.setText("Read");
        BTNREAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREADActionPerformed(evt);
            }
        });

        BTNEXIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNEXIT.setText("Keluar");
        BTNEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(BTNSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(BTNDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(BTNEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BTNREAD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(BTNEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNSAVE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNDELETE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNREAD)
                    .addComponent(BTNEDIT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNEXIT)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TXTNIK04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNIK04ActionPerformed(evt);
            }
        });

        TXTNAMA04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNAMA04ActionPerformed(evt);
            }
        });

        TXTJNSMEMBER04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTJNSMEMBER04ActionPerformed(evt);
            }
        });

        TXTMERK04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTMERK04ActionPerformed(evt);
            }
        });

        TXTTIPE04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTIPE04ActionPerformed(evt);
            }
        });

        TXTHARGA04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHARGA04ActionPerformed(evt);
            }
        });

        TXTTOTBIA04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTOTBIA04ActionPerformed(evt);
            }
        });

        tbljersey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIK Cust", "Nama Cust", "Jenis Member", "Merk Jersey", "Tipe Jersey", "Harga Jersey", "Total Biaya"
            }
        ));
        jScrollPane2.setViewportView(tbljersey);

        BTNCEKNIK.setText("Cek NIK");
        BTNCEKNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKNIKActionPerformed(evt);
            }
        });

        BTNCEKNAMA.setText("Cek Nama");
        BTNCEKNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKNAMAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTNAMA04, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(TXTNIK04))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BTNCEKNIK, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(BTNCEKNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTJNSMEMBER04, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTTOTBIA04, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTHARGA04, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTMERK04, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTTIPE04, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(TXTNIK04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKNIK))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TXTNAMA04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKNAMA))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(TXTJNSMEMBER04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(TXTMERK04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(TXTTIPE04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(TXTHARGA04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(TXTTOTBIA04, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTNIK04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNIK04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNIK04ActionPerformed

    private void TXTNAMA04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNAMA04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNAMA04ActionPerformed

    private void TXTJNSMEMBER04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTJNSMEMBER04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTJNSMEMBER04ActionPerformed

    private void TXTMERK04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTMERK04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTMERK04ActionPerformed

    private void TXTTIPE04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTIPE04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTIPE04ActionPerformed

    private void TXTHARGA04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHARGA04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTHARGA04ActionPerformed

    private void TXTTOTBIA04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTOTBIA04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTOTBIA04ActionPerformed

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("INSERT INTO tb_cetakreport(nik,nama,jenismember,merkjersey,tipejersey,hargajersey,totalbiaya)" + "VALUES (?,?,?,?,?,?,?)");

            pStatement.setString(1, TXTNIK04.getText());
            pStatement.setString(2, TXTNAMA04.getText());
            pStatement.setString(3, TXTJNSMEMBER04.getText());
            pStatement.setString(4, TXTMERK04.getText());
            pStatement.setString(5, TXTTIPE04.getText());
            pStatement.setString(6, TXTHARGA04.getText());
            pStatement.setString(7, TXTTOTBIA04.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTNIK04.setText("");
            TXTNAMA04.setText("");
            TXTJNSMEMBER04.setText("");
            TXTMERK04.setText("");
            TXTTIPE04.setText("");
            TXTHARGA04.setText("");
            TXTTOTBIA04.setText("");

        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }

        tbljersey.setValueAt(TXTNIK04.getText(), baris, 0);
        tbljersey.setValueAt(TXTNAMA04.getText(), baris, 1);
        tbljersey.setValueAt(TXTJNSMEMBER04.getText(), baris, 2);
        tbljersey.setValueAt(TXTMERK04.getText(), baris, 3);
        tbljersey.setValueAt(TXTTIPE04.getText(), baris, 4);
        tbljersey.setValueAt(TXTHARGA04.getText(), baris, 5);
        tbljersey.setValueAt(TXTTOTBIA04.getText(), baris, 6);

        baris=baris+1;
      
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pStatement = null;
            String sql ="DELETE FROM tb_cetakreport WHERE nik=? ";
            pStatement = Lconnection.prepareStatement(sql);

            //pStatement.setString(1, TXTNIK04);

            int intTambah= pStatement.executeUpdate();
            if (intTambah>0)
            JOptionPane.showMessageDialog(this,
                "Edit sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Edit gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }

        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 0);
        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 1);
        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 2);
        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 3);
        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 4);
        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 5);
        tbljersey.setValueAt (null, tbljersey.getSelectedRow(), 6);
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("UPDATE tb_cetakreport SET nama=?,jenismember=?,merkjersey=?,tipejersey=?,hargajersey=?,totalbiaya=? WHERE nik=?");

            pStatement.setString(1, TXTNIK04.getText());
            pStatement.setString(2, TXTNAMA04.getText());
            pStatement.setString(3, TXTJNSMEMBER04.getText());
            pStatement.setString(4, TXTMERK04.getText());
            pStatement.setString(5, TXTTIPE04.getText());
            pStatement.setString(6, TXTHARGA04.getText());
            pStatement.setString(7, TXTTOTBIA04.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTNIK04.setText("");
            TXTNAMA04.setText("");
            TXTJNSMEMBER04.setText("");
            TXTMERK04.setText("");
            TXTTIPE04.setText("");
            TXTHARGA04.setText("");
            TXTTOTBIA04.setText("");

        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNREADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNREADActionPerformed

    private void BTNEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEXITActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNEXITActionPerformed

    private void BTNCEKNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKNIKActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery (" Select * from tb_cetakreport" + "where nik like('%" + TXTNIK04.getText() + "%')");
            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTNIK04.setText(rs.getString("nik"));
                TXTNAMA04.setText(rs.getString("nama"));
                TXTJNSMEMBER04.setText(rs.getString("jenismember"));
                TXTMERK04.setText(rs.getString("merkjersey"));
                TXTTIPE04.setText(rs.getString("tipejersey"));
                TXTHARGA04.setText(rs.getString("hargajersey"));
                TXTTOTBIA04.setText(rs.getString("totalbiaya"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTNIK04.setText("");
                TXTNAMA04.setText("");
                TXTJNSMEMBER04.setText("");
                TXTMERK04.setText("");
                TXTTIPE04.setText("");
                TXTHARGA04.setText("");
                TXTTOTBIA04.setText("");
                TXTNAMA04.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKNIKActionPerformed

    private void BTNCEKNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKNAMAActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from tb_cetakreport" + "where nama like('%" +TXTNAMA04.getText() + "%')");

            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTNIK04.setText(rs.getString("nik"));
                TXTNAMA04.setText(rs.getString("nama"));
                TXTJNSMEMBER04.setText(rs.getString("jenismember"));
                TXTMERK04.setText(rs.getString("merkjersey"));
                TXTTIPE04.setText(rs.getString("tipejersey"));
                TXTHARGA04.setText(rs.getString("hargajersey"));
                TXTTOTBIA04.setText(rs.getString("totalbiaya"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTNIK04.setText("");
                TXTNAMA04.setText("");
                TXTJNSMEMBER04.setText("");
                TXTMERK04.setText("");
                TXTTIPE04.setText("");
                TXTHARGA04.setText("");
                TXTTOTBIA04.setText("");
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKNAMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCEKNAMA;
    private javax.swing.JButton BTNCEKNIK;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNEXIT;
    private javax.swing.JButton BTNREAD;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JTextField TXTHARGA04;
    private javax.swing.JTextField TXTJNSMEMBER04;
    private javax.swing.JTextField TXTMERK04;
    private javax.swing.JTextField TXTNAMA04;
    private javax.swing.JTextField TXTNIK04;
    private javax.swing.JTextField TXTTIPE04;
    private javax.swing.JTextField TXTTOTBIA04;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbljersey;
    // End of variables declaration//GEN-END:variables

    private Object[][] getData(){ 
 
        String user="root";         
        String pswd ="";         
        String host="localhost";         
        String db="db_jerseybola";
        String url=""; 
 
        Object[][] data1= null; 
 
        try {             
            Class.forName("com.mysql.jdbc.Driver"); 
 
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user +                   
            "&password="+ pswd;             
            Connection conn=DriverManager.getConnection(url); 
 
            Statement st = conn.createStatement();             
            ResultSet rs = st.executeQuery("SELECT * FROM tb_cetakreport"); 
 
            rs.last();             
            int rowCount= rs.getRow();             
            rs.beforeFirst(); 
 
            data1= new Object[rowCount][7];             
            int no=-1;             
            while (rs.next()) {                 
            no=no+1;                 
            data1[no][0]=rs.getString("nik");                 
            data1[no][1]=rs.getString("nama");                 
            data1[no][2]=rs.getString("jenismember");                 
            data1[no][3]=rs.getString("merkjersey");
            data1[no][4]=rs.getString("tipejersey");
            data1[no][5]=rs.getString("hargajersey");
            data1[no][6]=rs.getString("totalbiaya");
            } 
 
          st.close();           
          conn.close(); 
 
            } 
 
            catch(ClassNotFoundException e) {             
                System.out.println("jdbc.Driver tidak ditemukan");        
            } 
 
            catch (SQLException e){             
                System.out.println("koneksi gagal " + e.toString()); 
 
            } 
 
            return data1;     
           } 
 
           private void tampilTabel() { 
 
           String[] columnNames = {"nik", "nama", "jenismember", "merkjersey", "tipejersey", "hargajersey", "totalbiaya"}; 
 
           JTable table = new JTable(getData(), columnNames);                  
           jScrollPane2.setViewportView(table);     
           } 
}
