/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_Programming2;

import java.sql.*; 
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
/**
 *
 * @author User
 */
public class DataJersey extends javax.swing.JFrame {
   String user="root";         
   String pswd ="";         
   String host="localhost";         
   String db="db_jerseybola";         
   String url=""; 
   private Connection Lconnection=null;
   private JTable table=null;
    /**
     * Creates new form TBDataJersey
     */
    public DataJersey() {
        initComponents();
         
        Dimension screenSize =
        Toolkit.getDefaultToolkit().getScreenSize();       
         Dimension frameSize = this.getSize();
         if (frameSize.height > screenSize.height) {
             frameSize.height = screenSize.height;
         }
         if (frameSize.width > screenSize.width) {
             frameSize.width = screenSize.width;
         }
          this.setLocation(
                 (screenSize.width - frameSize.width) / 2,
                 (screenSize.height - frameSize.height) / 2);
         
         try { 
            Class.forName("com.mysql.jdbc.Driver");             
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd; 
            Lconnection=DriverManager.getConnection(url);         
        } 
        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        }  
        catch (SQLException e){             
            System.out.println("koneksi gagal:" + e.toString());         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Jlabel0 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        TXTKODEJERSEY = new javax.swing.JTextField();
        TXTMERKJERSEY = new javax.swing.JTextField();
        TXTTIPEJERSEY = new javax.swing.JTextField();
        TXTHARGAJERSEY = new javax.swing.JTextField();
        BTNPROSES = new javax.swing.JButton();
        BTNCEKKODE = new javax.swing.JButton();
        BTNCEKMERK = new javax.swing.JButton();
        BTNSAVE = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Backup_of_nunez.jpg")); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Jlabel0.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Yes.jpg")); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Data Jersey");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Kode Jersey");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Merk Jersey");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Tipe Jersey");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Harga Jersey");

        TXTKODEJERSEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTKODEJERSEYActionPerformed(evt);
            }
        });

        TXTMERKJERSEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTMERKJERSEYActionPerformed(evt);
            }
        });

        TXTTIPEJERSEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTIPEJERSEYActionPerformed(evt);
            }
        });

        TXTHARGAJERSEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHARGAJERSEYActionPerformed(evt);
            }
        });

        BTNPROSES.setBackground(new java.awt.Color(0, 255, 204));
        BTNPROSES.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        BTNPROSES.setText("Proses");
        BTNPROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPROSESActionPerformed(evt);
            }
        });

        BTNCEKKODE.setText("Cek Kode");
        BTNCEKKODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKKODEActionPerformed(evt);
            }
        });

        BTNCEKMERK.setText("Cek Merk");
        BTNCEKMERK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKMERKActionPerformed(evt);
            }
        });

        BTNSAVE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNSAVE.setText("Simpan");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        BTNEDIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNEDIT.setText("Edit");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNDELETE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNDELETE.setText("Hapus");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTTIPEJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TXTMERKJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BTNCEKMERK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXTHARGAJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(TXTKODEJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNCEKKODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jlabel0)
                        .addGap(18, 18, 18)
                        .addComponent(BTNPROSES, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(BTNEDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33)
                                    .addComponent(TXTKODEJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNCEKKODE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTMERKJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34)
                                    .addComponent(BTNCEKMERK))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(TXTTIPEJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(TXTHARGAJERSEY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNPROSES, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(BTNSAVE)
                        .addGap(18, 18, 18)
                        .addComponent(BTNEDIT)
                        .addGap(18, 18, 18)
                        .addComponent(BTNDELETE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTKODEJERSEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTKODEJERSEYActionPerformed
        // TODO add your handling code here:
        String kdjersey, merkjersey, tpjersey;
        double hrgjersey;

        kdjersey=String.valueOf(TXTKODEJERSEY.getText());

        if(kdjersey.equals("INA011")){
            merkjersey ="Mills" ;
            tpjersey ="Original Replika";
            hrgjersey =850000;
        }else
        if(kdjersey.equals("LIV102")){
            merkjersey ="Nike" ;
            tpjersey ="Supporter Version";
            hrgjersey =960000;
        }else
        if(kdjersey.equals("MC081")){
            merkjersey ="Puma" ;
            tpjersey ="Tipe KW";
            hrgjersey =950000;
        }else
        if(kdjersey.equals("RMA045")){
            merkjersey ="Adidas" ;
            tpjersey ="KW Lokal";
            hrgjersey =200000;
        }else
        if(kdjersey.equals("ACM041")){
            merkjersey ="Adidas" ;
            tpjersey ="Player Issue";
            hrgjersey =1100000;
        }else
        if(kdjersey.equals("JUV105")){
            merkjersey ="Adidas" ;
            tpjersey ="Grade AAA";
            hrgjersey =1150000;
        }else {
            merkjersey ="Tidak ada" ;
            tpjersey ="Tidak ada";
            hrgjersey =0;
        }
        TXTMERKJERSEY.setText(""+merkjersey);
        TXTTIPEJERSEY.setText(""+tpjersey);
        TXTHARGAJERSEY.setText(""+hrgjersey);
    }//GEN-LAST:event_TXTKODEJERSEYActionPerformed

    private void TXTMERKJERSEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTMERKJERSEYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTMERKJERSEYActionPerformed

    private void TXTTIPEJERSEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTIPEJERSEYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTIPEJERSEYActionPerformed

    private void TXTHARGAJERSEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHARGAJERSEYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTHARGAJERSEYActionPerformed

    private void BTNPROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPROSESActionPerformed
        // TODO add your handling code here:
        String kdjersey, merkjersey, tpjersey;
        double hrgjersey;

        kdjersey=String.valueOf(TXTKODEJERSEY.getText());

        if(kdjersey.equals("INA011")){
            merkjersey ="Mills" ;
            tpjersey ="Original Replika";
            hrgjersey =850000;
        }else
        if(kdjersey.equals("LIV102")){
            merkjersey ="Nike" ;
            tpjersey ="Supporter Version";
            hrgjersey =960000;
        }else
        if(kdjersey.equals("MC081")){
            merkjersey ="Puma" ;
            tpjersey ="Tipe KW";
            hrgjersey =950000;
        }else
        if(kdjersey.equals("RMA045")){
            merkjersey ="Adidas" ;
            tpjersey ="KW Lokal";
            hrgjersey =200000;
        }else
        if(kdjersey.equals("ACM041")){
            merkjersey ="Adidas" ;
            tpjersey ="Player Issue";
            hrgjersey =1100000;
        }else
        if(kdjersey.equals("JUV105")){
            merkjersey ="Adidas" ;
            tpjersey ="Grade AAA";
            hrgjersey =1150000;
        }else {
            merkjersey ="Tidak ada" ;
            tpjersey ="Tidak ada";
            hrgjersey =0;
        }
        TXTMERKJERSEY.setText(""+merkjersey);
        TXTTIPEJERSEY.setText(""+tpjersey);
        TXTHARGAJERSEY.setText(""+hrgjersey);
    }//GEN-LAST:event_BTNPROSESActionPerformed

    private void BTNCEKKODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKKODEActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery (" Select * from tb_datajersey" + "where kodejersey like('%" + TXTKODEJERSEY.getText() + "%')");
            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTKODEJERSEY.setText(rs.getString("kodejersey"));
                TXTMERKJERSEY.setText(rs.getString("merkjersey"));
                TXTTIPEJERSEY.setText(rs.getString("tipejersey"));
                TXTHARGAJERSEY.setText(rs.getString("hargajersey"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTKODEJERSEY.setText("");
                TXTMERKJERSEY.setText("");
                TXTTIPEJERSEY.setText("");
                TXTHARGAJERSEY.setText("");
                TXTKODEJERSEY.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKKODEActionPerformed

    private void BTNCEKMERKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKMERKActionPerformed
        // TODO add your handling code here:
          try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from tb_datajersey" + "where nama like('%" +TXTMERKJERSEY.getText() + "%')");

            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTKODEJERSEY.setText(rs.getString("kodejersey"));
                TXTMERKJERSEY.setText(rs.getString("merkjersey"));
                TXTTIPEJERSEY.setText(rs.getString("tipejersey"));
                TXTHARGAJERSEY.setText(rs.getString("hargajersey"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTKODEJERSEY.setText("");
                TXTMERKJERSEY.setText("");
                TXTTIPEJERSEY.setText("");
                TXTHARGAJERSEY.setText("");
                TXTMERKJERSEY.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKMERKActionPerformed

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("INSERT INTO tb_datajersey(kodejersey,merkjersey,tipejersey,hargajersey)" + "VALUES (?,?,?,?)");

            pStatement.setString(1, TXTKODEJERSEY.getText());
            pStatement.setString(2, TXTMERKJERSEY.getText());
            pStatement.setString(3, TXTTIPEJERSEY.getText());
            pStatement.setString(4, TXTHARGAJERSEY.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

             TXTKODEJERSEY.setText("");
             TXTMERKJERSEY.setText("");
             TXTTIPEJERSEY.setText("");
             TXTHARGAJERSEY.setText("");

        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("UPDATE tb_datajersey SET merkjersey=?,tipejersey=?,hargajersey=? WHERE kodejersey=?");

            pStatement.setString(1, TXTKODEJERSEY.getText());
            pStatement.setString(2, TXTMERKJERSEY.getText());
            pStatement.setString(3, TXTTIPEJERSEY.getText());
            pStatement.setString(4, TXTHARGAJERSEY.getText());


            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTKODEJERSEY.setText("");
            TXTMERKJERSEY.setText("");
            TXTTIPEJERSEY.setText("");
            TXTHARGAJERSEY.setText("");

        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pStatement = null;
            String sql ="DELETE FROM tb_datajersey WHERE kodejersey=? ";
            pStatement = Lconnection.prepareStatement(sql);

            //pStatement.setString(1, TXTKODEJERSEY);

            int intTambah= pStatement.executeUpdate();
            if (intTambah>0)
            JOptionPane.showMessageDialog(this,
                "Edit sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Edit gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNDELETEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataJersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataJersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataJersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataJersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataJersey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCEKKODE;
    private javax.swing.JButton BTNCEKMERK;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNPROSES;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JLabel Jlabel0;
    private javax.swing.JTextField TXTHARGAJERSEY;
    private javax.swing.JTextField TXTKODEJERSEY;
    private javax.swing.JTextField TXTMERKJERSEY;
    private javax.swing.JTextField TXTTIPEJERSEY;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
