/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_Programming2;

/**
 *
 * @author User
 */
public class FormMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form TBMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNDJ = new javax.swing.JButton();
        BTNKONSUMEN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BTNREPORT = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNTRANSAKSI = new javax.swing.JButton();
        BTNREAD = new javax.swing.JButton();
        BTNEDITDATA = new javax.swing.JButton();
        BTNFORMLOGIN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BTNDJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNDJ.setText("Data Jersey");
        BTNDJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDJActionPerformed(evt);
            }
        });
        getContentPane().add(BTNDJ);
        BTNDJ.setBounds(20, 80, 140, 30);

        BTNKONSUMEN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNKONSUMEN.setText("Konsumen");
        BTNKONSUMEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKONSUMENActionPerformed(evt);
            }
        });
        getContentPane().add(BTNKONSUMEN);
        BTNKONSUMEN.setBounds(350, 80, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Marcus Sport Center");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 10, 190, 25);

        BTNREPORT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNREPORT.setText("Cetak Report");
        BTNREPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREPORTActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREPORT);
        BTNREPORT.setBounds(320, 140, 130, 30);

        BTNDELETE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNDELETE.setText("Delete Data");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNDELETE);
        BTNDELETE.setBounds(310, 200, 130, 30);

        BTNTRANSAKSI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNTRANSAKSI.setText("Transaksi");
        BTNTRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTRANSAKSIActionPerformed(evt);
            }
        });
        getContentPane().add(BTNTRANSAKSI);
        BTNTRANSAKSI.setBounds(50, 140, 140, 30);

        BTNREAD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNREAD.setText("Read Data");
        BTNREAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREADActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREAD);
        BTNREAD.setBounds(80, 200, 130, 30);

        BTNEDITDATA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNEDITDATA.setText("Edit Data");
        BTNEDITDATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITDATAActionPerformed(evt);
            }
        });
        getContentPane().add(BTNEDITDATA);
        BTNEDITDATA.setBounds(280, 260, 110, 30);

        BTNFORMLOGIN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNFORMLOGIN.setText("Form Login");
        BTNFORMLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNFORMLOGINActionPerformed(evt);
            }
        });
        getContentPane().add(BTNFORMLOGIN);
        BTNFORMLOGIN.setBounds(120, 260, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Leicester 22-23.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        new CetakReport().setVisible(true);
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void BTNKONSUMENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKONSUMENActionPerformed
        // TODO add your handling code here:
        new Konsumen().setVisible(true);
    }//GEN-LAST:event_BTNKONSUMENActionPerformed

    private void BTNDJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDJActionPerformed
        // TODO add your handling code here:
        new DataJersey().setVisible(true);
    }//GEN-LAST:event_BTNDJActionPerformed

    private void BTNTRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTRANSAKSIActionPerformed
        // TODO add your handling code here:
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_BTNTRANSAKSIActionPerformed

    private void BTNREPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREPORTActionPerformed
        // TODO add your handling code here:
        new CetakReport().setVisible(true);
    }//GEN-LAST:event_BTNREPORTActionPerformed

    private void BTNREADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREADActionPerformed
        // TODO add your handling code here:
        new CetakReport().setVisible(true);
    }//GEN-LAST:event_BTNREADActionPerformed

    private void BTNEDITDATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITDATAActionPerformed
        // TODO add your handling code here:
        new CetakReport().setVisible(true);
    }//GEN-LAST:event_BTNEDITDATAActionPerformed

    private void BTNFORMLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNFORMLOGINActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true); 
    }//GEN-LAST:event_BTNFORMLOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNDJ;
    private javax.swing.JButton BTNEDITDATA;
    private javax.swing.JButton BTNFORMLOGIN;
    private javax.swing.JButton BTNKONSUMEN;
    private javax.swing.JButton BTNREAD;
    private javax.swing.JButton BTNREPORT;
    private javax.swing.JButton BTNTRANSAKSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
