/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_Programming2;

import java.sql.*; 
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
/**
 *
 * @author User
 */
public class Konsumen extends javax.swing.JFrame {
   String user="root";         
   String pswd ="";         
   String host="localhost";         
   String db="db_jerseybola";         
   String url=""; 
   private Connection Lconnection=null;
   private JTable table=null;
    /**
     * Creates new form TBKonsumen
     */
    public Konsumen() {
        initComponents();   
        
        Dimension screenSize =
        Toolkit.getDefaultToolkit().getScreenSize();       
         Dimension frameSize = this.getSize();
         if (frameSize.height > screenSize.height) {
             frameSize.height = screenSize.height;
         }
         if (frameSize.width > screenSize.width) {
             frameSize.width = screenSize.width;
         }
          this.setLocation(
                 (screenSize.width - frameSize.width) / 2,
                 (screenSize.height - frameSize.height) / 2);
         
         try { 
            Class.forName("com.mysql.jdbc.Driver");             
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd; 
            Lconnection=DriverManager.getConnection(url);         
        } 
        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        }  
        catch (SQLException e){             
            System.out.println("koneksi gagal:" + e.toString());         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TXTNIK = new javax.swing.JTextField();
        TXTNAMA = new javax.swing.JTextField();
        CBJNSMEMBER = new javax.swing.JComboBox<>();
        TXTPOT02 = new javax.swing.JTextField();
        Jlabel0 = new javax.swing.JLabel();
        BTNPROSES02 = new javax.swing.JButton();
        BTNSAVE = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNCEKNIK = new javax.swing.JButton();
        BTNCEKNAMA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Haaland.jpg")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Konsumen");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIK");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Jenis Member");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Potongan");

        CBJNSMEMBER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Dipilih", "Original Replika", "Supporter Version", "Tipe KW", "KW Lokal", "Player Issue", "Grade AAA" }));
        CBJNSMEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBJNSMEMBERActionPerformed(evt);
            }
        });

        Jlabel0.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Yes.jpg")); // NOI18N

        BTNPROSES02.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        BTNPROSES02.setText("Proses");
        BTNPROSES02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPROSES02ActionPerformed(evt);
            }
        });

        BTNSAVE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNSAVE.setText("Simpan");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        BTNEDIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNEDIT.setText("Edit");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNDELETE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNDELETE.setText("Hapus");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        BTNCEKNIK.setText("Cek NIK");
        BTNCEKNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKNIKActionPerformed(evt);
            }
        });

        BTNCEKNAMA.setText("Cek Nama");
        BTNCEKNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKNAMAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTPOT02)
                                    .addComponent(CBJNSMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCEKNIK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNCEKNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Jlabel0)
                .addGap(18, 18, 18)
                .addComponent(BTNPROSES02, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSAVE)
                    .addComponent(BTNDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TXTNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKNIK))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKNAMA))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(CBJNSMEMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(TXTPOT02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Jlabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNPROSES02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(BTNSAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNEDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNDELETE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBJNSMEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBJNSMEMBERActionPerformed
        // TODO add your handling code here:
        String nik,nama,jnsmember;
        double potongan;

        jnsmember=String.valueOf(CBJNSMEMBER.getSelectedItem());

        if(jnsmember.equals("Original Replika")){
            nik = "19456730871";
            nama = "Indra Veto" ;
            potongan = 60;
        }else
        if(jnsmember.equals("Supporter Version")){
            nik = "1946732911";
            nama = "Galung Arya";
            potongan = 56;
        }else
        if(jnsmember.equals("Tipe KW")){
            nik = "19477300290";
            nama = "Karno Sudirjo";
            potongan = 28;
        }else
        if(jnsmember.equals("KW Lokal")){
            nik = "20487309100";
            nama ="Saka Putra";
            potongan = 20;
        }else
        if(jnsmember.equals("Player Issue")){
            nik = "20487309134";
            nama ="Esteban Nino";
            potongan = 65;
        }else
        if(jnsmember.equals("Grade AAA")){
            nik = "20487309294";
            nama ="Refal Kusumowijoyo";
            potongan = 50;
        }else {
            nik =
            nama = "Tidak ada";
            potongan = 0;
        }

        TXTNIK.setText(""+nik);
        TXTNAMA.setText(""+nama);
        TXTPOT02.setText(""+potongan);
    }//GEN-LAST:event_CBJNSMEMBERActionPerformed

    private void BTNPROSES02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPROSES02ActionPerformed
        // TODO add your handling code here:
        String nik,nama,jnsmember;
        double potongan;

        jnsmember=String.valueOf(CBJNSMEMBER.getSelectedItem());

        if(jnsmember.equals("Original Replika")){
            nik = "19456730871";
            nama = "Indra Veto" ;
            potongan = 60;
        }else
        if(jnsmember.equals("Supporter Version")){
            nik = "1946732911";
            nama = "Galung Arya";
            potongan = 56;
        }else
        if(jnsmember.equals("Tipe KW")){
            nik = "19477300290";
            nama = "Karno Sudirjo";
            potongan = 28;
        }else
        if(jnsmember.equals("KW Lokal")){
            nik = "20487309100";
            nama ="Saka Putra";
            potongan = 20;
        }else
        if(jnsmember.equals("Player Issue")){
            nik = "20487309134";
            nama ="Esteban Nino";
            potongan = 65;
        }else
        if(jnsmember.equals("Grade AAA")){
            nik = "20487309294";
            nama ="Refal Kusumowijoyo";
            potongan = 50;
        }else {
            nik =
            nama = "Tidak ada";
            potongan = 0;
        }

        TXTNIK.setText(""+nik);
        TXTNAMA.setText(""+nama);
        TXTPOT02.setText(""+potongan);
    }//GEN-LAST:event_BTNPROSES02ActionPerformed

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("INSERT INTO tb_konsumen(nik,nama,jenismember,potongan)" + "VALUES (?,?,?,?)");

            pStatement.setString(1, TXTNIK.getText());
            pStatement.setString(2, TXTNAMA.getText());
            pStatement.setString(3, (String) CBJNSMEMBER.getSelectedItem());
            pStatement.setString(4, TXTPOT02.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTNIK.setText("");
            TXTNAMA.setText("");
            CBJNSMEMBER.setSelectedItem("");
            TXTPOT02.setText("");

        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("UPDATE tb_konsumen SET nama=?,jenismember=?,potongan=? WHERE nik=?");

            pStatement.setString(1, TXTNIK.getText());
            pStatement.setString(2, TXTNAMA.getText());
            pStatement.setString(3, (String) CBJNSMEMBER.getSelectedItem());
            pStatement.setString(4, TXTPOT02.getText());

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTNIK.setText("");
            TXTNAMA.setText("");
            CBJNSMEMBER.setSelectedItem("");
            TXTPOT02.setText("");

        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pStatement = null;
            String sql ="DELETE FROM tb_konsumen WHERE nik=? ";
            pStatement = Lconnection.prepareStatement(sql);

            //pStatement.setString(1, TXTNIK);

            int intTambah= pStatement.executeUpdate();
            if (intTambah>0)
            JOptionPane.showMessageDialog(this,
                "Edit sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Edit gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void BTNCEKNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKNIKActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery (" Select * from tb_cetakreport" + "where nik like('%" + TXTNIK.getText() + "%')");
            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTNIK.setText(rs.getString("nik"));
                TXTNAMA.setText(rs.getString("nama"));
                CBJNSMEMBER.setSelectedItem(rs.getString("jenismember"));
                TXTPOT02.setText(rs.getString("potongan"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTNIK.setText("");
                TXTNAMA.setText("");
                CBJNSMEMBER.setSelectedItem("");
                TXTPOT02.setText("");
                TXTNAMA.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKNIKActionPerformed

    private void BTNCEKNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKNAMAActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from tb_cetakreport" + "where nama like('%" +TXTNAMA.getText() + "%')");

            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTNIK.setText(rs.getString("nik"));
                TXTNAMA.setText(rs.getString("nama"));
                CBJNSMEMBER.setSelectedItem(rs.getString("jenismember"));
                TXTPOT02.setText(rs.getString("potongan"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTNIK.setText("");
                TXTNAMA.setText("");
                CBJNSMEMBER.setSelectedItem("");
                TXTPOT02.setText("");
                TXTNAMA.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKNAMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konsumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCEKNAMA;
    private javax.swing.JButton BTNCEKNIK;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNPROSES02;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JComboBox<String> CBJNSMEMBER;
    private javax.swing.JLabel Jlabel0;
    private javax.swing.JTextField TXTNAMA;
    private javax.swing.JTextField TXTNIK;
    private javax.swing.JTextField TXTPOT02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
