/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_Programming2;

import java.sql.*; 
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import javax.swing.JOptionPane; 
import javax.swing.JTable; 
/**
 *
 * @author User
 */
public class Transaksi extends javax.swing.JFrame {
   String user="root";         
   String pswd ="";         
   String host="localhost";         
   String db="db_jerseybola";         
   String url=""; 
   private Connection Lconnection=null;
   private JTable table=null;
    /**
     * Creates new form TBTransaksi
     */
    public Transaksi() {
        initComponents(); 
         
        Dimension screenSize =
        Toolkit.getDefaultToolkit().getScreenSize();       
         Dimension frameSize = this.getSize();
         if (frameSize.height > screenSize.height) {
             frameSize.height = screenSize.height;
         }
         if (frameSize.width > screenSize.width) {
             frameSize.width = screenSize.width;
         }
          this.setLocation(
                 (screenSize.width - frameSize.width) / 2,
                 (screenSize.height - frameSize.height) / 2);
         
         try { 
            Class.forName("com.mysql.jdbc.Driver");             
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd; 
            Lconnection=DriverManager.getConnection(url);         
        } 
        catch(ClassNotFoundException e) {             
            System.out.println("Driver tidak ditemukan");         
        }  
        catch (SQLException e){             
            System.out.println("koneksi gagal:" + e.toString());         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jlabel0 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BTNPROSES03 = new javax.swing.JButton();
        TXTMERK03 = new javax.swing.JTextField();
        TXTHARGA03 = new javax.swing.JTextField();
        TXTJMLHBELI = new javax.swing.JTextField();
        TXTPOT = new javax.swing.JTextField();
        TXTTOTBIA = new javax.swing.JTextField();
        BTNSAVE = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNCEKMERK = new javax.swing.JButton();
        BTNCEKHARGA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Tchouameni.jpg")); // NOI18N

        Jlabel0.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Screenshots\\Yes.jpg")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Transaksi");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Merk Jersey");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Harga Jersey");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Jumlah Beli");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("Potongan");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Total Biaya");

        BTNPROSES03.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        BTNPROSES03.setText("Proses");
        BTNPROSES03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPROSES03ActionPerformed(evt);
            }
        });

        TXTHARGA03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTHARGA03ActionPerformed(evt);
            }
        });

        TXTJMLHBELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTJMLHBELIActionPerformed(evt);
            }
        });

        TXTPOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPOTActionPerformed(evt);
            }
        });

        TXTTOTBIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTOTBIAActionPerformed(evt);
            }
        });

        BTNSAVE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNSAVE.setText("Simpan");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        BTNEDIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNEDIT.setText("Edit");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNDELETE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNDELETE.setText("Hapus");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        BTNCEKMERK.setText("Cek Merk");
        BTNCEKMERK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKMERKActionPerformed(evt);
            }
        });

        BTNCEKHARGA.setText("Cek Harga");
        BTNCEKHARGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCEKHARGAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(TXTHARGA03, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TXTJMLHBELI, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTTOTBIA, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TXTPOT))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNCEKHARGA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)
                                .addComponent(TXTMERK03, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNCEKMERK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Jlabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNPROSES03, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNSAVE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TXTMERK03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKMERK))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TXTHARGA03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNCEKHARGA))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TXTJMLHBELI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TXTPOT, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TXTTOTBIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jlabel0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNSAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNEDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNDELETE)
                        .addGap(36, 36, 36))
                    .addComponent(BTNPROSES03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNPROSES03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPROSES03ActionPerformed
        // TODO add your handling code here:
        String merkjersey;
        double hrgjersey, potongan, jmlhbeli = 5, result;

        merkjersey = String.valueOf(TXTMERK03.getText());
        hrgjersey = Double.parseDouble(TXTJMLHBELI.getText());
        potongan = Double.parseDouble(TXTPOT.getText());
        result = Double.parseDouble(TXTTOTBIA.getText());

        result = (jmlhbeli * hrgjersey) - potongan;

        TXTMERK03.setText(""+merkjersey);
        TXTHARGA03.setText(""+hrgjersey);
        TXTPOT.setText(""+potongan);
        TXTTOTBIA.setText(""+result);
    }//GEN-LAST:event_BTNPROSES03ActionPerformed

    private void TXTHARGA03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTHARGA03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTHARGA03ActionPerformed

    private void TXTJMLHBELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTJMLHBELIActionPerformed
        // TODO add your handling code here:
        String merkjersey;
        double jmlhbeli,result,hrgjersey = 0,potongan = 0;

        merkjersey=String.valueOf(TXTMERK03.getText());
        jmlhbeli = Double.parseDouble(TXTJMLHBELI.getText());
        potongan = Double.parseDouble(TXTPOT.getText());
        result = Double.parseDouble(TXTTOTBIA.getText());

        result = (jmlhbeli * hrgjersey) - potongan;

        TXTMERK03.setText(""+merkjersey);
        TXTHARGA03.setText(""+hrgjersey);
        TXTPOT.setText(""+potongan);
        TXTTOTBIA.setText(""+result);
    }//GEN-LAST:event_TXTJMLHBELIActionPerformed

    private void TXTPOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPOTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPOTActionPerformed

    private void TXTTOTBIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTOTBIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTOTBIAActionPerformed

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("INSERT INTO tb_transaksi(merkjersey,hargajersey,jumlahbeli,potongan,totalbiaya)" + "VALUES (?,?,?,?,?)");

            pStatement.setString(1, TXTMERK03.getText());
            pStatement.setString(2, TXTHARGA03.getText());
            pStatement.setString(3, TXTJMLHBELI.getText());
            pStatement.setString(4, TXTPOT.getText());
            pStatement.setString(5, TXTTOTBIA.getText());
          

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTMERK03.setText("");
            TXTHARGA03.setText("");
            TXTJMLHBELI.setText("");
            TXTPOT.setText("");
            TXTTOTBIA.setText("");
         
        }
        catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://"+ host +"/"+ db + "?user=" + user + "&password="+ pswd;
            Connection conn=DriverManager.getConnection(url);
            PreparedStatement pStatement = conn.prepareStatement("UPDATE tb_transaksi SET hargajersey=?,jumlahbeli=?,potongan=?,totalbiaya=? WHERE merkjersey=?");

            pStatement.setString(1, TXTMERK03.getText());
            pStatement.setString(2, TXTHARGA03.getText());
            pStatement.setString(3, TXTJMLHBELI.getText());
            pStatement.setString(4, TXTPOT.getText());
            pStatement.setString(5, TXTTOTBIA.getText());
          

            if (pStatement.executeUpdate()>0)
            JOptionPane.showMessageDialog(this,
                "Penambahan sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Penambahan gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();
            conn.close();

            TXTMERK03.setText("");
            TXTHARGA03.setText("");
            TXTJMLHBELI.setText("");
            TXTPOT.setText("");
            TXTTOTBIA.setText("");
            
        }
         catch(ClassNotFoundException e) {
            System.out.println("jdbc.Driver tidak ditemukan");
        }
        
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement pStatement = null;
            String sql ="DELETE FROM tb_transaksi WHERE merkjersey=? ";
            pStatement = Lconnection.prepareStatement(sql);

            //pStatement.setString(1, TXTMERK03);

            int intTambah= pStatement.executeUpdate();
            if (intTambah>0)
            JOptionPane.showMessageDialog(this,
                "Edit sukses", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
            else
            JOptionPane.showMessageDialog(this,
                "Edit gagal", "Informasi",
                JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

        }

        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNDELETEActionPerformed

    private void BTNCEKMERKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKMERKActionPerformed
        // TODO add your handling code here:
         try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery (" Select * from tb_transaksi" + "where merkjersey like('%" + TXTMERK03.getText() + "%')");
            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTMERK03.setText(rs.getString("merkjersey"));
                TXTHARGA03.setText(rs.getString("hargajersey"));
                TXTJMLHBELI.setText(rs.getString("jumlahbeli"));
                TXTPOT.setText(rs.getString("potongan"));
                TXTTOTBIA.setText(rs.getString("totalbiaya"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTMERK03.setText("");
                TXTHARGA03.setText("");
                TXTJMLHBELI.setText("");
                TXTPOT.setText("");
                TXTTOTBIA.setText("");
                TXTHARGA03.requestFocus();
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKMERKActionPerformed

    private void BTNCEKHARGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCEKHARGAActionPerformed
        // TODO add your handling code here:
         try {
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery
            ("Select * from tb_cetakreport" + "where hargajersey like('%" +TXTHARGA03.getText() + "%')");

            if (rs.next()) {
                BTNEDIT.setEnabled(true);
                TXTMERK03.setText(rs.getString("merkjersey"));
                TXTHARGA03.setText(rs.getString("hargajersey"));
                TXTJMLHBELI.setText(rs.getString("jumlahbeli"));
                TXTPOT.setText(rs.getString("potongan"));
                TXTTOTBIA.setText(rs.getString("totalbiaya"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                BTNEDIT.setEnabled(false);
                TXTMERK03.setText("");
                TXTHARGA03.setText("");
                TXTJMLHBELI.setText("");
                TXTPOT.setText("");
                TXTTOTBIA.setText("");
            }
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_BTNCEKHARGAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCEKHARGA;
    private javax.swing.JButton BTNCEKMERK;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNPROSES03;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JLabel Jlabel0;
    private javax.swing.JTextField TXTHARGA03;
    private javax.swing.JTextField TXTJMLHBELI;
    private javax.swing.JTextField TXTMERK03;
    private javax.swing.JTextField TXTPOT;
    private javax.swing.JTextField TXTTOTBIA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

 }
